version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
      - 443:443
    volumes: # 挂载 宿主机:容器
      - /root/moyublog/nginx/html:/usr/share/nginx/html
      - /root/moyublog/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/moyublog/nginx/ssl:/etc/nginx/ssl
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=
  moyublog:
    image: moyublog:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8080:8080
    volumes: # 挂载 宿主机:容器
      - /root/moyublog/logs:/logs
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    depends_on: # 依赖与mysql，其实可以不填，默认已经表示可以
      - mysql
