spring:
  datasource:
    # 本地环境
    # 直接连远程 mysql 5.7
    username:
    password:
    url: jdbc:mysql://120.26.218.121:3306/moyublog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 20000

  jackson:
    time-zone: GMT+8