spring:
  datasource:
    # mysql 5.7
    username: ''
    password: ''
    url: jdbc:mysql://mysql:3306/moyublog?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 20000
  jackson:
    time-zone: GMT+8